[package]
name = "jolt-samples"
version = "0.1.0"
edition = "2021"
authors = ["cohaereo <cohaereo@protonmail.com>"]

[dependencies]
jolt = { path = ".." }
three-d = { version = "0.16.3", features = ["egui-gui"] }
rand = "0.8.5"
